baseURL = "https://daisy.github.io/ace"
languageCode = "en-us"
title = "Ace, by DAISY"
description = "Hi"
theme = "daisy"
publishDir = "site"

[params]
  description = "**[Ace](/ace)**, an accessibility checker for EPUB!  \n\
  A **[DAISY Consortium](http://daisy.org)** project. \n\
  Latest version: v0.7.0 (beta 3)"
